<html>

<head>
    <link href="./styles/game.css" type="text/css" rel="stylesheet">
    <link href="./styles/victory.css" type="text/css" rel="stylesheet">
    <script src="./js/jquery-3.5.0.min.js"></script>
    <script src="./js/jquery-ui.min.js"></script>

    <title>Quarto</title>
    
    <script>
    $(document).ready(function() {
        $(".board").html(sessionStorage.getItem("board"));
        var nickname = JSON.parse(sessionStorage.getItem("nicknames"));
        var points = JSON.parse(sessionStorage.getItem("points"));

        var winner = parseInt(sessionStorage.getItem("winner"));
        $("#winner").html(nickname[winner-1]);
        
        $("#player1").html(`${nickname[0]} - ${points[0]}`)
        $("#player2").html(`${nickname[1]} - ${points[1]}`);

        var victoryArray = JSON.parse(sessionStorage.getItem("victory"));
        console.log(victoryArray);
        switch (victoryArray[0]) {
            case "row":
                for (let j = 1; j <= 4; ++j) {
                    $(`#${victoryArray[1]}-${j}`).addClass("marked");
                }
                break;
            case "col":
                for (let i = 1; i <= 4; ++i) {
                    $(`#${i}-${victoryArray[1]}`).addClass("marked");
                }
                break;
            case "diag":
                for (let i = 1; i <= 4; ++i) {
                    if (victoryArray[1] == 1) {
                        $(`#${i}-${i}`).addClass("marked");
                    } else if (victoryArray[1] == 2) {
                        $(`#${i}-${5-i}`).addClass("marked");
                    } else {
                        alert("Something went wrong...")
                    }
                }
                break;
            default:
                alert("something went wrong...")
        }
    });

    function goToStartPage() {
        if (confirm('Are you sure you want to turn back to the start page? This will restart your game.')) {
            window.location = 'index.php';
        }
    }
    </script>

</head>

<body>
    <header>
        <br>
        <h1 onclick="goToStartPage()"> QUARTO </h1>
    </header>

    <div id="titleMargin" style="margin-top: 20px;"></div>
    <div id="playerNames" style="height: 60px; margin: auto; width: 100%; text-align:center">
        Winner:
        <span id="winner" style="display:inline-block;" class="playerSelected"> </span>
    </div>
    <div style="width:100%; margin:auto; text-align:center">
        <div style="width:20%; display:inline-block; position:absolute;"></div>
        <div style="width:55%; display:inline-block">
            <table class="board">
                <!-- Generated by JavaScript -->
            </table>
        </div>
        <div style="width:20%; text-align:center; display:inline-block; position:absolute; text-align:left;">
            <font size="+2"> <b>Games won:</b>  </font> <br>
            <label id="player1"> <!-- Generated by JavaScript --> </label> <br>
            <label id="player2"> <!-- Generated by JavaScript --> </label>
        </div>
<!--  -->
        <div style="width:20%">
    </div>
    
    <div id="titleMargin" style="margin-top: 50px;"></div>
    <div style="width:100%; margin:auto; text-align:center">
        <button onclick="window.location = `game.php`">New Game</button>
    </div>

</body>

</html>